1.1
jwvg0425/milewski-ctfp-pdf-kr pull request #3
Opened 2019-06-19 16:13 UTC by stet-stet

검토를 위해 일부러 미완으로 둔 곳이 몇 군데 있습니다. 검토 부탁드립니다.

2019-06-19 16:14 UTC, stet-stet commented on src/preamble.tex
> +\newcommand{\trIdentity}{항등사상} % identity morphism
"항등"으로 바꾸고, Identity가 "항등사상" 혹은 "항등원"이라는 의미로 쓰인 곳에는 "사상" "원" 등을 뒤에 붙일 예정입니다.

2019-06-19 16:14 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +항등 조건은 의사하스켈로 다음과 같이 쓸 수 있다.
\trIdentity 조건

2019-06-19 16:18 UTC, stet-stet commented
좀 더 프로젝트 전체에 관련되는 문제들도 있는데요,
1. "function"을 어떤 곳에 "함수", 어떤 곳에 "사상"이라고 쓸까요?
2. "identity function"은 언제 "항등 사상", 언제 "\trIdentity" 사상이라고 쓸까요?
3. 빌드를 해 본 결과 \tr~~~~ 이후에 띄어쓰기가 제대로 되지 않는 버그가 있습니다. 어떻게 해결해야 할까요?

3에 대해서는 일단 내일 조금 더 찾아보려 합니다.

2019-06-20 04:55 UTC, jwvg0425 requested changes
일일히 잡기가 힘들어서 빠뜨린 게 좀 있을 것 같은데, \tr 시리즈 뒤에 붙는 자동 조사가 많이 빠진 것 같습니다 ㅠㅠ 요걸 자동으로 처리해주는 스크립트를 짜는게 나을 수도요

그리고, 목차에 보이는(그리고 챕터 시작에 보이는) 챕터명 번역이 빠진 것 같습니다. ctfp.tex 파일에서 수정하시면 돼요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +그러나, \trCategory의 정수는 \trComposition이다. 또는, 이렇게 말하는 걸 더 좋아한다면, \trComposition의 정수는 \trCategory다.
원문에 있는 강조가 빠진 것 같습니다.  `그러나, \trCategory의 정수는 \empth{\trComposition}이다.` 가 되어야 할 듯

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +$A$ to $C$로 가는 \trArrow가(\trComposition이) 있어야 한다.
$A$ to $C$로 가는 => $A$ 에서 $C$로 가는, \trArrow가 => \trArrow\가, \trComposition이 => \trComposition\이

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trCategory는 \newterm{\trObject}\와 그들 사이를 잇는 \newterm{\trArrow}로 이루어져 있다.
\newterm{\trArrow}로 -> \newterm{\trArrow}\로

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +그래서 \trCategory\는 그림으로 나타내기 쉽다. \trObject는 원이나 점으로,
\trObject는 ->  \trObject\는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +즉 \trObject $A$에서 \trObject $B$로 가는 \trArrow가 하나, \trObject $B$에서 \trObject $C$로 가는 \trArrow가 하나 있다면,
\trArrow가 -> \trArrow\가
앞에 하나 뒤에 하나 두 개 있네요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이 도식은 \trIdentityMorphism(후술)이 없어서 완전한 \trCategory는 아니다.}
\trCategory는 =>  \trCategory\는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +수학에서는 함수 이름 사이에 작은 원을 그려서 \trComposition을 표시한다 ($g \circ f$).
\trComposition\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +독자는 아래와 같은 유닉스(Unix) pipe notation(피드백 바람)에 친숙할 지도 모르겠다.
유닉스 파이프 명령 정도로 번역되는게 익숙한 용어인 것 같습니다.

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +$g \circ f$를 ``g \emph{전에} f.''라고 읽으면 좀 덜 헷갈린다.
이건 어렵네요 ㅠㅠ 한국어 어순으로는 표현이 힘든데..  ``g \emph{하기 전에} f. 한다'' 같은 표현은 어떨까요?

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +C언어에서도 오른쪽에서 왼쪽 순서의 \trComposition을 볼 수 있다. (\code{g(f(a))})
\trComposition\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +면, 이 둘의 \trComposition은 다음과 같다.
\trComposition\은

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +C++ 표준 라이브러리에 함수 두 개를 받아서 그 \trComposition을 리턴하는 템플릿이 있다 말할 수 있으면 참 좋겠으나, 그런 건 없다.
\trComposition\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +비슷하게:
개인적으로 한국어 작문에서 콜론은 사용되지 않는 용법이라고 생각해서, 번역할 때 콜론은 없는게 좋다고 생각합니다(의견 부탁드림)
`비슷하게, g를 다음과 같이 선언할 수 있다.` 정도로 풀어 쓰는게 한국어 용례에 더 잘 맞는 것 같아요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이들의 \trComposition은:
이 문장도
`그리고 이들의 \trComposition\은 아래와 같다`
정도가 낫지 않을까요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +사실 하스켈은 유니코드를 지원하기 때문에, \trComposition을 다음과 같이 쓸 수 있다.
\trComposition\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +두 함수 사이에 온점( . )이나 유니코드 원(◦)을 넢어서 \trComposition할 수 있다.
넢어서 => 넣어서 오타 난 것 같아용

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +So here's the first Haskell lesson: 더블 콜론은 ``~~형을 가지는''이라는 뜻이다.
자, 여기서 첫번째 하스켈 수업이다. 정도로 번역해도 괜찮지 않을까요?
뒷문장은 ~형을 가지는 보다는 ~ 타입을 가지는 이라고 쓰는게 더 이해가 잘 될 것 같습니당

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trCategory에 속한 \trComposition이 만족해야 할 매우 중요할 성질이 두 가지 있다.
\trComposition\이

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trComposition은 결\trComposition을 만족한다. \trComposition 가능한 세 개의 \trMorphism $f$, $g$, $h$가 있을 때
\trComposition\은

associative가 결\trComposition 이라고 적힌 것은 조금 이상한 것 같습니다 ㅋㅋ trAssociative 를 따로 만들거나 해야 하지 않을까요.

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +(즉 양 끝의 \trObject가 서로 잘 맞아떨어질 때), \trComposition하기 위해 괄호가 필요하지 않다.
\trComposition하기 위해 괄호가 필요하지 않다. > 이들의 \trComposition\은 괄호가 필요 없다. 라고 하면 좀 더 깔끔할 것 같아요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +(의사) 하스켈에서는
(의사) 하스켈에서는 다음과 같이 쓸 수 있다. 는 어떨까요? 문장이 끊기는 기분이라

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +결\trComposition은 함수를 다룰 때는 당연해 보이나, 다른 카테고리에서는 꼭 그렇지만은 않을 수 있다.
이것두 결\trComposition 은 이상한 것 같아요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +모든 \trObject $A$에 대해, \trComposition의 \trUnit이 되는 \trArrow가 존재한다.
\trUnit\이, \trArrow\가

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이 \trArrow는 $A$에서 자신으로 다시 돌아간다.
\trArrow\는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trComposition의 \trUnit이라는 것은, $A$에서 시작하거나 끝나는 \trArrow와 \trComposition한 결과가 그 각각의 화살표라는 의미이다.
\trUnit\이라 는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trObject $A$와 연관된 \trUnit \trArrow는 $\idarrow[A]$ ($A$에의 \newterm{\trIdentity}) 라고 부른다.
\trArrow\는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +함수와 관련된 작업을 할 때, \trIdentity\을 나타내는 \trArrow\는 그 인자를 그대로 리턴하는 항등함수로 구현된다.
`~이며 ~` 꼴로 문장이 끊기는 기분이라 끝에 ~이다. 를 붙여주고 다음 문장이 진행되면 좋을 것 같습니다.

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이렇듯, 하스켈에서는 다형적 함수를 매우 쉽게 다를 수 있다.
꼭 이럴 필요는 없겠지만 원문 비유랑 느낌이 비슷하게 `하스켈에서 다형적 함수 다루기는 누워서 떡먹기다` 정도 표현은 어떨까요?

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +실제로도 이렇게 간단하지는 않다.
`실제로는` 이 더 문맥상 맞는 것 같아용

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이 구현은 인자의 형에 따라 달라지는 것이 아니므로, 보편 다형적이다.
보편 다형적이라는 말이 쉽게 이해하기 힘들 것 같은데 좋은 대체어가 생각이 안 나네요.. ㅠㅠ 뭐가 좋을까요?

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +구상(concrete) 자료형의 이름은 항상 대문자로, 타입 변수의 이름은 항상 소문자로 시작함을 기억하자.
하스켈에서 concrete type은 타입 변수가 아닌 구체화된 타입 자체를 뜻합니다. ( Int / Char 등의 명시적인 타입은 concrete type, f :: a -> b 등에서의 a,b 는 type variable) 한국어로 적합한 표현을 잘 모르겠네요.. 그냥 '타입' 혹은 '자료형'이라고 하고 concrete 부분은 생략해도 무방한 것 같긴 합니다

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +구상(concrete) 자료형의 이름은 항상 대문자로, 타입 변수의 이름은 항상 소문자로 시작함을 기억하자.
LYAH(http://learnyouahaskell.com/chapters) 라는 널리 쓰이는 하스켈 lecture 에서 그냥 type이라고 쓰고 concrete type이라는 표현을 안 쓴 것으로 봐서 생략해도 이해하는데는 무리가 없을 것 같네요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이로써 두 번째 하스켈 강좌를 끝마쳤다.
비슷하게 그냥 이렇게 표현해도 상관없을 것 같고 강좌 / 강의 보다는 수업 이라는 표현이 좀 더 친근감 있는 것 같아요(의견)

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +어쨌든, 항등함수는 고계함수의 인자, 혹은 리턴값으로 쓰기 유용하다.
고계 함수도 tr~~ 로 빼는게 좋을 것 같습니다. 일반적으로 익숙치 않은 용어일 거라.. \trHigherOrderFunction(higher-order function) 과 같이 표현해주면 어떨까요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +어쨌든, 항등함수는 고계함수의 인자, 혹은 리턴값으로 쓰기 유용하다.
또, argument 와 parameter 의 번역어는 통일되어야 할 것 같은데 이 용어들이 쓰인 부분들도 다 \trArgument, \trParameter 로 해주면 번역하기 편하지 않을까 싶네요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +그리고, 모든 \trObject에는 \trComposition의 \trUnit인 \trIdentity \trArrow가 있다.
결\trComposition, \은\는\이\가 조사 수정이 필요할 것 같습니다

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +단지 우리의 뇌가 구조 안 잡힌 코드를 잘 처리해낼 수 없어서다.
'구조 잡히지 않은' 혹은 '무질서한' 이 나을 거 같아요

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trCategoryTheory 상에서 \trObject는 추상적이고 모호한 객체이다.
\trObject\는

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +이 \trObject가 다른 \trObject와 어떻게 관련되는지, 즉 \trArrow로 어떤 식으로 연결되어 있는지만을 알 수 있다.
\trObject\가, \trArrow\로

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +만약 어떤 \trObject를 다른 \trObject와 \trComposition할 때 \trObject의 구현을 들여다봐야 한다면
\trObject\를

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +  당신이 가장 좋아하는 프로그래밍 언어로 \trIdentity을 구현하라.
\trIdentity\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +  당신이 가장 좋아하는 프로그래밍 언어로 두 함수의 \trComposition을 리턴하는 함수를 작성하라.
\trComposition\을

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +  인자로 두 함수가 주어지고, 이 두 함수의 \trComposition이 리턴되어야 한다.
\trComposition\이

2019-06-20 04:55 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +  바로 위 문제에서 짠 함수가 항등성을 만족하는지 테스트하는 코드를 짜려고 노력하라.
~하는지 노력하는 / 시도하는 프로그램을 작성하라. 가 맞는 것 같아요

2019-06-20 04:55 UTC, jwvg0425 commented on src/preamble.tex
> +\newcommand{\trIdentity}{항등사상} % identity morphism
\trSideEffect가 카테고리가 되어부렷어요.. 부작용 or 사이드 이펙트로 바꿔주셔야 할 듯

2019-06-20 04:55 UTC, jwvg0425 commented on src/preamble.tex
> +\newcommand{\trExpression}{구}
보통 trExpression => 표현식 정도로 번역되는 것 같습니다

2019-06-20 04:55 UTC, jwvg0425 commented on src/preamble.tex
> +\newcommand{\trStatement}{문}
그리고 요게 보통 문장으로 번역되는 듯

2019-06-20 04:58 UTC, jwvg0425 commented
추가로 쓰신 의견에 대해서는
1~2. function은 항상 함수로 번역해도 문제 없지 않을까요? morphism은 사상, function은 함수로  책 내용 상에서도 구분되어서 쓰고 있다고 생각합니다. identity function => 항등 함수. 로 항상 번역되어도 의미가 달라지는 경우는 없는 것 같아요(최소한 챕터 1에서는)

3. 저도 이게 문제였는데.. 어케 해결하는지 모르겠어서 냅뒀어요 ㅠㅠ

2019-06-23 06:44 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +\trComposition은 결\trComposition을 만족한다. \trComposition 가능한 세 개의 \trMorphism $f$, $g$, $h$가 있을 때
문서 내의 "합성"을 전부 replace 기능으로 \trComposition으로 대체했더니 저 짝이 났네요 ㅋㅋㅋㅋㅋㅋㅋㅋ 간만에 소리 내어 웃었습니다. \trAssociative를 {결합성}으로 뺄게요

2019-06-23 06:45 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +(의사) 하스켈에서는
콜론 문법도 그렇고, 정말 직역하면 좀 그렇네요...! 수정하였습니다

2019-06-23 06:47 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +실제로도 이렇게 간단하지는 않다.
수정하겠습니다!

2019-06-23 06:49 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +이 구현은 인자의 형에 따라 달라지는 것이 아니므로, 보편 다형적이다.
원문인 universally polymorphic을 보고 머리가 새하얘지는 기분이었습니다 ㅠㅠㅠ 음...이건 다른 곳에 한 번 물어보는 편이 좋을 것 같습니다.

2019-06-23 06:50 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +이렇듯, 하스켈에서는 다형적 함수를 매우 쉽게 다를 수 있다.
수정했어요!

2019-06-23 06:55 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +구상(concrete) 자료형의 이름은 항상 대문자로, 타입 변수의 이름은 항상 소문자로 시작함을 기억하자.
음...개인적으로는 혼동의 여지가 있어 조금 리스키해 보이기는 합니다. 혹시 "int, char과 같은 자료형의 이름은 ~~" 같이 설명을 앞에 덧붙이면 어떨까요?

2019-06-23 06:56 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +이로써 두 번째 하스켈 강좌를 끝마쳤다.
반영하였습니다!

2019-06-23 07:07 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +단지 우리의 뇌가 구조 안 잡힌 코드를 잘 처리해낼 수 없어서다.
"무질서한"으로 가겠습니다!

2019-06-23 07:07 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +  바로 위 문제에서 짠 함수가 항등성을 만족하는지 테스트하는 코드를 짜려고 노력하라.
반영했습니다!

2019-06-23 07:09 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +$g \circ f$를 ``g \emph{전에} f.''라고 읽으면 좀 덜 헷갈린다.
조금 더 과감하게 g 괄호 f 괄호 닫고 (ㅋㅋㅋㅋㅋㅋㅋㅋ)같은 방법도 있을 것 같아요! 일단 안전하게 "하기 전에"로 반영해놓겠습니다

2019-06-23 07:11 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +(즉 양 끝의 \trObject가 서로 잘 맞아떨어질 때), \trComposition하기 위해 괄호가 필요하지 않다.
"이들의 \trComposition에는 괄호가 필요 없다"는 어떻게 생각되시나요

2019-06-24 03:54 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +하스켈에서 함수 정의는 함수의 이름, 그리고 이를 뒤따르는 형식\trParameter\로 이루어진다.
https://ko.wikipedia.org/wiki/%EB%A7%A4%EA%B0%9C%EB%B3%80%EC%88%98_(%EC%BB%B4%ED%93%A8%ED%84%B0_%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D)

위키백과에서는 parameter = 매개 변수, argument = 전달 인자 로 사용하네요. 다른 소스들 찾아봐도 이게 가장 널리 쓰이는 용어인 것 같습니다(argument의 경우는 그냥 인자 라고 쓰는 번역도 많이 보이네요) 일단 parameter / argument를 동일한 이름으로 번역하고 `형식\trParameter`라고 쓰는 건 별로 좋지 않은 것 같습니다.

2019-06-24 03:56 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +$g \circ f$를 ``g \emph{전에} f.''라고 읽으면 좀 덜 헷갈린다.
그것은.. 너무 과감한 것 같네요 ㅋㅋㅋ

2019-06-24 03:57 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +구상(concrete) 자료형의 이름은 항상 대문자로, 타입 변수의 이름은 항상 소문자로 시작함을 기억하자.
그것도 괜찮은 것 같습니다. `Int, Char과 같은 구체적인 자료형의 이름은` 정도로 풀어써주면 괜찬을듯

2019-06-24 03:59 UTC, jwvg0425 commented on src/content/1.1/category-the-essence-of-composition.tex
> +(즉 양 끝의 \trObject가 서로 잘 맞아떨어질 때), \trComposition하기 위해 괄호가 필요하지 않다.
좋네요. 그게 더 깔끔한 거 같아요

2019-06-24 11:48 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +구상(concrete) 자료형의 이름은 항상 대문자로, 타입 변수의 이름은 항상 소문자로 시작함을 기억하자.
조금 찾아보니 하스켈에서는 Int가 아니라 Integer라고 쓰는 모양이라, "Integer, Char과 같은~~~"으로 수정하였습니다.

2019-06-24 12:29 UTC, stet-stet commented on src/content/1.1/category-the-essence-of-composition.tex
> +하스켈에서 함수 정의는 함수의 이름, 그리고 이를 뒤따르는 형식\trParameter\로 이루어진다.
argument를 "인자"라고 번역한 후, \trFormalParameter를 {형식 매개 변수}로 뺐습니다. \trParameter가 본 챕터에서 사용되지는 않으나, 일단 preamble에 넣어두겠습니다. 

"전달 인자"라고 일괄적으로 번역한다면, 일부 문장의 경우 번역이 조금 불편해집니다. 이를테면 
> 나중에 다\trArgument 함수를 정의할 때 이 사실을 알 수 있다.
이 문장의 원문이
> (you’ll see that later, when we define functions of multiple arguments)
인데요, "다인자 함수"보다 간결하고 알기 쉬운 번역이 사실 없는 듯 해요

한편 "인자"라고만 번역하는 데에도 불편함은 있을 수 있지만, 최소한 이렇게 하면 "다\trArgument"나, "\trArgumentPrefix \trArgument" 등과 같이 쓸 수 있는 여지는 생기니까요.

사실 이렇게 여러 가지로 번역할 수 있는 영단어의 경우 애초에 \tr~~~ 적용을 되도록 안 하는 게 좋지 않나~~하는 생각도 리뷰를 받고 나니 들기 시작했습니다.

2019-06-24 12:47 UTC, jwvg0425 approved these changes

2019-06-24 12:50 UTC, merged

2019-06-27 15:18 UTC, seungwonpark commented
조금 뒷북인 감이 있지만,
3. 보통 이 경우 \xspace 라는 명령어를 사용하시면 됩니다. `\newcommand{\gb}{Great Britain\xspace}` 처럼요.

preamble에 `\usepackage{xspace}`가 있어야 합니다. 자세한 내용은 xspace 패키지의 documentation을 참고하세요: `texdoc xspace` 
<img width="581" alt="Screen Shot 2019-06-28 at 12 15 25 AM" src="https://user-images.githubusercontent.com/13394294/60278159-da875a80-9939-11e9-8f9f-c0921eb11fc4.png">