1.3
jwvg0425/milewski-ctfp-pdf-kr pull request #6
Opened 2019-07-08 13:46 UTC by stet-stet

번역 퀄리티가 1.1만큼은 아닌 것 같아 조금 죄책감도 듭니다.
여쭈어보고자 하는 부분이 꽤 많습니다. 특히, preamble의 경우 용어 번역하기 애매한 게 하도 많아서, 그 쪽은 평소보다 집중적으로 검토해주실 수 없을까 합니다.
감사합니다.

2019-07-09 03:59 UTC, jwvg0425 commented on src/preamble.tex
> +\newcommand{\trCurrying}{currying} % currying
Currying은 그냥 그대로 읽어서 커링으로 번역하는게 꽤 정착이 되어 있는 느낌이라 음차해도 될 것 같습니다.

2019-07-09 04:00 UTC, jwvg0425 commented on src/preamble.tex
> +\newcommand{\trPointWiseEquality}{점별 동등성} % point-wise equality
이 'point'들이 들어가 있는 용어들이 어렵네요.. 일단 point-free 접독립(오타) => 점독립 이고 용어가 뭐가 좋을지는 ㅠㅠ 너무 어렵네요 이 용어들은

2019-07-09 04:01 UTC, jwvg0425 commented on src/preamble.tex
> +%여쭈어보고 하는 게 좋을 거 같은데, 결국 모든 용어 뒤에 \xspace가 있어야 하는 게 맞나요?
\trA\trB 식으로 커맨드 두개가 연달아 있을 때 자동으로 공백 넣어주고 아니면 안 넣어주는 것으로 아는데, 넣어서 손해볼 건 없으니 모든 용어 뒤에 넣어도 괜찮지 않나 싶긴 합니다

2019-07-09 04:05 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\trObject\를 \trArrow\로 이어서 \trCategory\를 만들 수 있다.
'잇는 것 만으로도' 같은 표현이 좀 더 원문의 뉘앙스가 잘 살 것 같아요

2019-07-09 05:31 UTC, jwvg0425 requested changes

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +먼저, 그래프의 각 노드(!!절점?)에 \trIdentity  \trArrow\를 더한다.
절점?은 아무 상관 없는 것 같은데 어떤 의미로 들어갔나용?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +위 과정을 다른 관점에서 이렇게도 볼 수 있다. 우리는 그래프의 각 꼭지점마다 \trObject\를,
위에서는 노드로 번역했는데 여기서는 꼭지점으로 번역이 되어서, 용어를 통일하는게 좋을 것 같습니다. /trNode로 빼는 것도 괜찮을듯

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +합성할 수 있는 변을 이어놓은 것 하나마다 \trMorphism\를 가지는 \trCategory\를 만들었다.
합성 -> \trComposition?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이러한 \trCategory\는 \trFreeConstruction의 예시이다. \trFreeConstruction이란,
문장 구조가 비슷하게 반복되는 것 같아서, `이러한 \trCategory\는 \trFreeConstruction의 예시이다.` => `이는 \trFreeConstruction의 예시이기도 하다` 는 어떨까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +미완성인 구조가 주어지면 이를 확장하여, 그 구조의 성질을 만족시키면서 최소의 (!!item)을 포함하게 하는 것을 말한다. %item 뭐라 번역할까요, 원소? 내용물?
으 애매하네요; 원소라고 하면 집합이 생각나는데 집합보다 더 추상적인 이야기인 것 같은데 내용물이라고 하면 또 좀 안 와닿는 것 같고.. 그래도 그나마 내용물이 좀 더 나은 것 같습니다

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이러한 성질을 만족하는 \trCategory\를 ``\trThin''다고 부른다. \trPreorder\는 \trThin\은 \trCategory다.
``\trThin''다(thin) 라고 원문 영어 표현이 뭔지를 처음에 병기해주면 좋을 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\newterm{\trHomSet}이라고 읽으며, $\cat{C}(a, b)$ (또는 $\mathbf{Hom}_{\cat{C}}(a, b)$)라고 쓴다.
(56번째줄) 내에서 => 내의,  (57번째줄) 읽으며 => 부르며 가 좀 더 자연스러울 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\newterm{\trHomSet}이라고 읽으며, $\cat{C}(a, b)$ (또는 $\mathbf{Hom}_{\cat{C}}(a, b)$)라고 쓴다.
또 homSet의 원문 영어 표현 병기도 있으면 좋겠네요 \newTerm{\trHomSet}(hom-set) 같은 식으로

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +한편, \trPreorder에는 루프가 있을 수 있다. 이는 \trPartialOrder에는 있을 수 없다.
루프 => 사이클

루프는 일반적으로 여기서 이야기하는 항등 함수(어떤 노드 A에서 A 자신으로 돌아가는 엣지)를 뜻하기 때문에 혼동의 여지가 있습니다. 원문이 여러 edge로 구성된 사이클이 존재할 수 없다는 의미이므로 사이클로 번역하는게 정확할 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +문자열, 리스트, foldable data structures, 동시성 프로그래밍에서 사용하는 퓨쳐(future), functional reactive programming에서의 이벤트(events)
foldable.. 너무 노답인데요.. ㅠㅠ 이걸 어떻게 번역하지.. fold에 해당하는 한국어 표현이 아마 없을텐데.. `접을 수 있는(foldable)` 이라고 번역하는 방법이 있고 그냥 `폴더블(foldable)` 혹은 `폴드(fold) 가능한 / 할 수 있는` 이라고 번역하는 방법이 있을 것 같네요..  어느 것 하나 마음에 들지는 않지만..

FRP는 보통 함수형 리액티브 프로그래밍 정도로 번역하는 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +예를 들어, 자연수와 영의 집합과 덧셈에 대해 \trMonoid\를 이룬다.
(의견) `0 이상의 정수 집합` or `0 이상의 정수로 구성된 집합` 같은 표현은 어떨까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\trNeutralElement\는 영이다. 왜냐하면,
`영이다` => `0이다`. 라고 쓰는게 더 이해가 잘 될 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\trCurrying에 관한 얘기를 하고 나면 완벽하게 말이 됨을 볼 수 있을 것이다.
여기도 첫 등장이라 영어 표현 병기해주면 좋을 것 같아요. \trCurrying(currying) 같은 식

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\trArrow\를 가진 표현은 기본적으로 두 가지로 해석될 수 있다. 첫째는 다\trArgument 함수,
'multple arrow' 가 그냥 arrow가 되었어요. 여러 개의 \trArrow\를 가진 표현은 ~ ?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +하스켈에서는 \code{mempty}와 \code{mappend}의 \trMonoid 관련 성질을 나태낼 방법이 없음에 주목하라.
(오타) 나태낼 -> 나타낼
(의견) ~하라. 는 식의 표현은 약간 영어식 표현에 가까운 것 같은데, `관련 성질을 나타낼 방법이 없다.` 로 그냥 단정짓거나 혹은 `관련 성질을 나타낼 방법이 없음에 주의하자.` 같은 건 어떨까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\section{집합으로써의 \trMonoid}
(오타, 문법?) ~로써는 뭔가를 도구로 사용할 때 강조를 위해 쓰는 말입니다. 이 경우 ~로서 가 맞는 표현입니다. 참고) https://ko.wiktionary.org/wiki/%EB%B6%80%EB%A1%9D:%EB%A7%9E%EC%B6%A4%EB%B2%95/%EB%A1%9C%EC%84%9C%EC%99%80_%EB%A1%9C%EC%8D%A8

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +하스켈의 클래스들은 C++ 클래스처럼 intrusive하지 않다.
intrusive 번역이 빠진것같아용..?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +하스켈의 syntax에 대해 한 마디 하고 지나가는 게 좋을 듯 하다. 임의의 중위연산자를 괄호로 싸면 그것은 이\trArgument 함수가 된다.
syntax -> 구문? 문법? 정도의 한국어로 번역하는게 좋지 않을까요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +하스켈의 syntax에 대해 한 마디 하고 지나가는 게 좋을 듯 하다. 임의의 중위연산자를 괄호로 싸면 그것은 이\trArgument 함수가 된다.
`이인자 함수`라는 표현이 약간 이해하기 힘들 것 같아요 `두 \trArgument를 받는 or 취하는 함수` 같은 표현은 어떨까요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +함수에 대한 \trArgument\가 쉽표나 괄호로 싸여 있지 않다.
(오타) 쉽표  -> 쉼표

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +함수에 대한 \trArgument\가 쉽표나 괄호로 싸여 있지 않다.
단순히 '함수에 대한' 이라고 하면 조금 이해하기 힘들어 보여요. `여기서 함수에 전달하는 \trArgument 사이에 쉼표를 쓰거나 \trArgument를 괄호로 감싸지 않는다` 식으로 풀어서 써주면 어떨지

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +전자는 \trCategory $\Hask$(끝나지 않는 계산 \trBottom\을 무시하면 $\Set$)에서의 \trMorphism의 동등성으로 해석할 수 있다.
`혹은\trBottom(끝나지 않는 계산을 뜻하는)을 무시했을 경우 $\Set$` 는 어떨까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\trArgument의 값이 가끔 \newterm{점}이라고 불리기도 하므로 (점 $x$에서 함수 $f$의 값), 이러한 표현은
point도 \trPoint로 묶는 건 어떨까요? 이 쪽 용어들은 나중에 고민이 좀 더 필요할 것 같은데.. 일단 이 용어들이 수학에서 함수 y = f(x) 의 각 'point(점) x(좌표평면 같은 걸 상상해보면)' 에 대한 함숫값 f(x)가 같다는 식의 표현 => pointwise equality, 이런 표현 없이 f = g 스타일의 함수 자체가 같다는 식의 표현(point 없는 표현 -> point-free) 에서 유래한 것으로 아는데 적합한 용어를 생각하기가 참 힘드네요.. 기존에 번역어가 있는 용어도 아닌 듯 하고

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +C++에서 \trMonoid 선언과 가장 비슷한 것은 아마 콘셉트(concepts)라는 proposed syntax이다.
'다음 표준에 제안된 문법인'  정도는 어떨까요?
`C++에서 \trMonoid 선언과 가장 비슷한 것은 아마 다음 표준에 제안된 문법중 하나인 콘셉트(concept)일 것이다`

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +C++에서 \trMonoid 선언과 가장 비슷한 것은 아마 콘셉트(concepts)라는 proposed syntax이다.
콘셉트는 그냥 콘셉트 음차로 번역하는게 나을듯

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +첫 선언은 값 템플릿을 사용하는데, 이 문법도 proposed다.
이 문법도 다음 표준에 제안되어 있는 상황이다. 정도?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +주어진 타입 \code{M}에 대해 \code{mempty}와 \code{mappend}에 대한 적절한 정의가 존재하는지 테스트하는 \trPredicatesㅣ다.
(오타) 맨 끝에 `ㅣ다`

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +주어진 타입 \code{M}에 대해 \code{mempty}와 \code{mappend}에 대한 적절한 정의가 존재하는지 테스트하는 \trPredicatesㅣ다.
테스트하는 => 확인하는, 검증하는?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +적절한 오버로드와 specialization을 제공하여서 \trMonoid 콘셉트\를 인스턴스화할 수 있다.
specialization => 특수화(템플릿 특수화) 가 주로 쓰는 번역어입니다

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +그러므로 우리는 관점을 살짝 바꾸어서, 집합 안에서 여러 가지를 ``움직이''거나 ``하나씩 미는'' 이항연산자를 생각해보자.
'하나씩' 이라는 말이 원문에는 딱히 없어서 약간 의미가 바뀐 느낌이 듭니다. 그냥 ``미는'' 으로 번역해도 되지 않을까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이를테면, 모든 자연수에 5를 더하는 연산을 생각해볼 수 있다. 이 연산을 통해 0은 5로, 1은 6으로, 2는 7로 사살된다.
사살된다 => 사상된다. 숫자가 죽어버렸어요.. ㅠㅠ
'대응된다' 라고 하면 좀 더 이해하기 쉬울 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +일반적으로, 어떤 수 $n$에 대해서도 $n$을 더하는 함수가 있다. 이 함수를 $n$의 \trAdder\라고 부른다.
``\trAdder'' ? 원문에 있는 강조가 빠졌어요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +즉 \trAdder의 \trComposition\과 덧셈에 적용되는 법칙들은 동치나 다름없다. 역시 좋다. 이제 덧셈을 함수의 \trComposition\로 바꾸어 볼 수 있다.
법칙들은 => 법칙은. '들'은 최대한 안 쓰는게 좋은 한국어 표현 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +그러나 이게 끝이 아니다. \trNeutralElement인 영의 \trAdder도 있다. 영을 더한다고 해서 움직여지는 건 아무 것도 없으므로,
영의 => 0의, 영을 => 0을. '0을 더하는 건 아무것도 움직이지 못하므로' 라는 표현은 어떨까요?
숫자는 숫자 기호로 표현하는게 덜 헷갈리는 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이를 통해서 \code{mappend}가 \trMonoid 집합의 원소를, 그 집합에 작용하는 사상으로 사상한다는 점을 알 수 있다.
`그 집합에 작용하는 함수로 사상한다`가 낫지 않을까요? 의미가 틀린 건 아니지만 원문에서도 function으로 명시하고 있기도 해서요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이제, 우리가 지금껏 자연수 집합에서 여러 가지를 해왔다는 사실을 잊고, 대신 이 집합을 \trMorphism\이(\trAdder\가) 많이 달린 \trObject\라고 생각하자.
`우리가 지금껏 자연수 집합에서 여러 가지를 해왔다는 사실을 잊고` => `지금껏 자연수 집합에서 여러 가지를 해왔다는 사실을 잊어버리고` 는 어떨까요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이런 질문을 할 수도 있다. 임의의 \trCategory적 \trMonoid(\trObject\가 하나인 \trCategory)로, 집합과 이항연산자가 들은 \trMonoid\를 유일하게 정의할 수 있을까??
?? => ? 물음표가 두개나 들어갔군요 ㅋㅋ

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이 \trMorphism들의 시작점과 끝 점이 항상 같은 \trObject이므로, \trComposition\은 항상 존재한다. %어라? starting point는 용어가 뭐였더라요...?
이전에는 source / target 이라는 표현을 썼었는데 원래는 각각 '원본', '대상' 이라는 번역을 했었어요. 여기서는 시작점/끝점이라고 하는게 더 이해하기 쉬워보이네요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +    변 없이 꼭짓점 하나만 가지는 그래프
위에서 언급한 꼭짓점 - 노드 번역어 문제(trNode)

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +    하나의 (유향) 변, 그리고 꼭짓점 하나를 가지는 그래프.
이것두요 \trNode, \trEdge 전부 번역어를 두는 건 어떤지? 아래쪽 264~268 라인까지 전부 동일한 문제

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +    포함 관계를 만족하는 집합의 집합. $A$의 원소가 모두 $B$의 원소라면 $A$가 $B$에 `포함된다'고 한다. %맞는 번역인가요?
맞는 것 같아요

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +  법 3(modulo 3)에 대한 덧셈을 \trMonoid \trCategory\로 표현하시오. %법 3이 맞는 표현은 맞는데, 저걸 들었을 때 감이 오시나요?
표현은 맞는데 이해하기 힘들 것 같아요. 수학적 배경이 좀 있는 사람만 이해할 듯한..
`3으로 나눈 나머지에 대한 덧셈`이라고 하면 어떨까요?

2019-07-09 05:31 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +  법 3(modulo 3)에 대한 덧셈을 \trMonoid \trCategory\로 표현하시오. %법 3이 맞는 표현은 맞는데, 저걸 들었을 때 감이 오시나요?
이것도 좀 오해할 소지가 있을 것 같은데.. 어렵네요

2019-07-15 13:43 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +먼저, 그래프의 각 노드(!!절점?)에 \trIdentity  \trArrow\를 더한다.
노드가 낫나, 절점이 낫나였어요. 일단 제 기억대로는 꼭짓점이 맞는 표현입니다. 실수에요 실수

2019-07-15 13:45 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +위 과정을 다른 관점에서 이렇게도 볼 수 있다. 우리는 그래프의 각 꼭지점마다 \trObject\를,
그래프 다룰 때 공식적인 용어는 꼭짓점인 것으로 알고 있습니다. 일단 꼭짓점으로 통일할게요

2019-07-15 13:53 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +미완성인 구조가 주어지면 이를 확장하여, 그 구조의 성질을 만족시키면서 최소의 (!!item)을 포함하게 하는 것을 말한다. %item 뭐라 번역할까요, 원소? 내용물?
만약에 전체 검수를 할 때가 생긴다면 다시 검토하면 좋을 듯 합니다. universally polymorphic같이...

2019-07-15 14:08 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +문자열, 리스트, foldable data structures, 동시성 프로그래밍에서 사용하는 퓨쳐(future), functional reactive programming에서의 이벤트(events)
일단 "이 용어에 대한 설명은 나중에 나올 거다" 라고 각주 붙이고, "접을 수 있는"으로 정리해놨어요. 구글링해보니 하스켈 이외에서의 용례는 거의 없다시피하네요...ㅠ

2019-07-15 14:08 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +예를 들어, 자연수와 영의 집합과 덧셈에 대해 \trMonoid\를 이룬다.
좋은 것 같습니다

2019-07-15 14:10 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +하스켈에서는 \code{mempty}와 \code{mappend}의 \trMonoid 관련 성질을 나태낼 방법이 없음에 주목하라.
반영했습니다!

2019-07-15 14:16 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +하스켈의 클래스들은 C++ 클래스처럼 intrusive하지 않다.
아....고민하다가 남았나봐요. "흉하다" "튀어나와 있다" 는 좀 아닌 것 같아서, "문법이 강제적이지 않다"로 적당히 의역했습니다.

2019-07-15 14:17 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +하스켈의 syntax에 대해 한 마디 하고 지나가는 게 좋을 듯 하다. 임의의 중위연산자를 괄호로 싸면 그것은 이\trArgument 함수가 된다.
각각 후자, 후자로 수정했습니다.

2019-07-15 14:21 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +함수에 대한 \trArgument\가 쉽표나 괄호로 싸여 있지 않다.
적용했습니다.

2019-07-15 14:22 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +전자는 \trCategory $\Hask$(끝나지 않는 계산 \trBottom\을 무시하면 $\Set$)에서의 \trMorphism의 동등성으로 해석할 수 있다.
\trBottom(끝나지 않는 계산을 뜻함) 할게요

2019-07-15 14:26 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +그러므로 우리는 관점을 살짝 바꾸어서, 집합 안에서 여러 가지를 ``움직이''거나 ``하나씩 미는'' 이항연산자를 생각해보자.
5로 더하는 거 보니 "하나씩" 미는 것두 아니네요...ㅠㅠㅠ 제 생각이 짧았습니다.

2019-07-15 14:50 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +즉 \trAdder의 \trComposition\과 덧셈에 적용되는 법칙들은 동치나 다름없다. 역시 좋다. 이제 덧셈을 함수의 \trComposition\로 바꾸어 볼 수 있다.
문서 전체를 뒤져서, 이건 도저히 못 빼겠다 하는 것 빼고는 다 빼 보았습니다. 복수를 나타내는 "들"을 찾기 위한 Ctrl+F 키워드입니다: 집합들을, \trMorphism들의, 수학자들, 집합보다 큰 것들,

2019-07-15 14:52 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +그러나 이게 끝이 아니다. \trNeutralElement인 영의 \trAdder도 있다. 영을 더한다고 해서 움직여지는 건 아무 것도 없으므로,
생각해보니 정말 그런 것 같습니다. 사실 영가산자 vs 0가산자가 좀 아리까리하긴 한데, 얘만 영으로 두기도 좀 그러니 일단 0가산자로 하겠습니다.

2019-07-15 14:54 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +이를 통해서 \code{mappend}가 \trMonoid 집합의 원소를, 그 집합에 작용하는 사상으로 사상한다는 점을 알 수 있다.
고쳤습니다. 찾아보니, map을 function보다 큰 개념으로 쓰는 컨텍스트가 존재하네요! 앞으로 조심해야겠습니다..

2019-07-15 14:56 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +이 \trMorphism들의 시작점과 끝 점이 항상 같은 \trObject이므로, \trComposition\은 항상 존재한다. %어라? starting point는 용어가 뭐였더라요...?
저는 개인적으로는 "원본/대상"보다는 (조금 informal할지언정 더 친숙한) 시작점, 끝 점이 좋은 것 같습니다.

2019-07-15 14:59 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +    하나의 (유향) 변, 그리고 꼭짓점 하나를 가지는 그래프.
음....알겠습니다. 일단 "node"는 꼭짓점, edge는 "간선"으로 둘게요

2019-07-15 14:59 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +  법 3(modulo 3)에 대한 덧셈을 \trMonoid \trCategory\로 표현하시오. %법 3이 맞는 표현은 맞는데, 저걸 들었을 때 감이 오시나요?
어려울 때는 footnote!(? 
지금 고친 파일은 어떻게 보시나요

2019-07-15 15:06 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +위 과정을 다른 관점에서 이렇게도 볼 수 있다. 우리는 그래프의 각 꼭지점마다 \trObject\를,
\trNode 만들었어요 \trEdge도요

2019-07-16 03:57 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +그러나 이게 끝이 아니다. \trNeutralElement인 영의 \trAdder도 있다. 영을 더한다고 해서 움직여지는 건 아무 것도 없으므로,
아 이게 또 좀 애매하긴 하군요.. 0가산자보단 영가산자가 나은 거 같은데 나머지 부분은 0이 더 나은거같고 ㅋㅋㅋ

2019-07-16 03:57 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +이 \trMorphism들의 시작점과 끝 점이 항상 같은 \trObject이므로, \trComposition\은 항상 존재한다. %어라? starting point는 용어가 뭐였더라요...?
저도 그런거 같긴 해요

2019-07-16 03:59 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +지금까지는 집합의 원소룰 가지고 ``익숙한'' 방식으로 \trMonoid\를 정의해보았다.
룰 => 를 오타났어용

2019-07-16 04:01 UTC, jwvg0425 requested changes

2019-07-16 04:01 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +지금까지는 집합의 원소룰 가지고 ``익숙한'' 방식으로 \trMonoid\를 정의해보았다.
룰 => 를 오타났어용

2019-07-16 04:01 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
>  \section{\trCategory\로써의 \trMonoid }
여기도 로써 => 로서인데 제가 놓쳤네요

2019-07-16 04:01 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +\caption{집합 내의 점과 \trMorphism\로써 보는 \trMonoid\trHomSet}
여기도 로써 => 로서

2019-07-16 04:01 UTC, jwvg0425 commented on src/content/1.3/categories-great-and-small.tex
> +  법 3(modulo 3)에 대한 덧셈을 \trMonoid \trCategory\로 표현하시오. %법 3이 맞는 표현은 맞는데, 저걸 들었을 때 감이 오시나요?
이건 괜찮은 것 같습니다.

2019-07-16 09:27 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +\trArgument의 값이 가끔 \newterm{점}이라고 불리기도 하므로 (점 $x$에서 함수 $f$의 값), 이러한 표현은
stet-stet:"일반명사 용어를 만들기 시작하면 언제 써야 하고 언제 안 써야 할 지 구분이 어렵다"
jwvg0425:있을지 없을지 모르겠지만 언젠가 전체 검수 한 번 싹 다 하면서 다시 검토하는 요소중 하나로(후략)

2019-07-16 14:36 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +그러나 이게 끝이 아니다. \trNeutralElement인 영의 \trAdder도 있다. 영을 더한다고 해서 움직여지는 건 아무 것도 없으므로,
거기만 영가산자 해둘게요!

2019-07-16 14:41 UTC, stet-stet commented on src/content/1.3/categories-great-and-small.tex
> +\caption{집합 내의 점과 \trMorphism\로써 보는 \trMonoid\trHomSet}
위쪽에도 로써가 하나 있기는 한데, 그거는 "다양한 예시들을 살펴봄으로써 ~~~할 수 있다"이고, 신분이나 지위, 위, 자격을 나타내는 것 같지 않으니 걔만은 그대로 두겠습니다. 그리고, 연습문제에도 올바르지 않은 "로써"가 있길래 아예 없앴습니다.

2019-07-17 05:03 UTC, jwvg0425 approved these changes

2019-07-17 05:03 UTC, jwvg0425 commented
1.3 끝! 와와~~

2019-07-17 09:12 UTC, merged